-- ============================================
-- FRANCOPHILE.CH - Liste des verbes PER
-- Verbes à maîtriser en 9e, 10e et 11e année
-- ============================================

-- ============================================
-- VERBES 9e ANNÉE (consolidation des bases)
-- ============================================

INSERT INTO verbes (infinitif, groupe, auxiliaire, annee_per, particularite) VALUES
-- Auxiliaires et semi-auxiliaires
('être', '3', 'avoir', '9', 'auxiliaire'),
('avoir', '3', 'avoir', '9', 'auxiliaire'),
('aller', '3', 'être', '9', 'semi-auxiliaire'),

-- 1er groupe - verbes réguliers essentiels
('aimer', '1', 'avoir', '9', NULL),
('chanter', '1', 'avoir', '9', NULL),
('danser', '1', 'avoir', '9', NULL),
('donner', '1', 'avoir', '9', NULL),
('écouter', '1', 'avoir', '9', NULL),
('fermer', '1', 'avoir', '9', NULL),
('jouer', '1', 'avoir', '9', NULL),
('marcher', '1', 'avoir', '9', NULL),
('parler', '1', 'avoir', '9', NULL),
('penser', '1', 'avoir', '9', NULL),
('porter', '1', 'avoir', '9', NULL),
('regarder', '1', 'avoir', '9', NULL),
('rester', '1', 'être', '9', NULL),
('tomber', '1', 'être', '9', NULL),
('travailler', '1', 'avoir', '9', NULL),
('trouver', '1', 'avoir', '9', NULL),

-- 1er groupe - verbes en -cer, -ger, -yer
('commencer', '1', 'avoir', '9', 'c cédille devant a/o'),
('manger', '1', 'avoir', '9', 'ge devant a/o'),
('voyager', '1', 'avoir', '9', 'ge devant a/o'),
('lancer', '1', 'avoir', '9', 'c cédille devant a/o'),
('placer', '1', 'avoir', '9', 'c cédille devant a/o'),
('nager', '1', 'avoir', '9', 'ge devant a/o'),
('payer', '1', 'avoir', '9', 'y devient i devant e muet'),
('essayer', '1', 'avoir', '9', 'y devient i devant e muet'),
('envoyer', '1', 'avoir', '9', 'futur irrégulier'),
('appuyer', '1', 'avoir', '9', 'y devient i devant e muet'),
('nettoyer', '1', 'avoir', '9', 'y devient i devant e muet'),

-- 1er groupe - verbes en -eler, -eter
('appeler', '1', 'avoir', '9', 'double l devant e muet'),
('jeter', '1', 'avoir', '9', 'double t devant e muet'),
('acheter', '1', 'avoir', '9', 'accent grave devant e muet'),

-- 2e groupe - verbes réguliers
('finir', '2', 'avoir', '9', NULL),
('choisir', '2', 'avoir', '9', NULL),
('réussir', '2', 'avoir', '9', NULL),
('grandir', '2', 'avoir', '9', NULL),
('grossir', '2', 'avoir', '9', NULL),
('maigrir', '2', 'avoir', '9', NULL),
('rougir', '2', 'avoir', '9', NULL),
('obéir', '2', 'avoir', '9', NULL),
('réfléchir', '2', 'avoir', '9', NULL),
('agir', '2', 'avoir', '9', NULL),
('bâtir', '2', 'avoir', '9', NULL),
('remplir', '2', 'avoir', '9', NULL),
('salir', '2', 'avoir', '9', NULL),

-- 3e groupe - verbes essentiels
('faire', '3', 'avoir', '9', NULL),
('dire', '3', 'avoir', '9', NULL),
('voir', '3', 'avoir', '9', NULL),
('venir', '3', 'être', '9', NULL),
('prendre', '3', 'avoir', '9', NULL),
('pouvoir', '3', 'avoir', '9', NULL),
('vouloir', '3', 'avoir', '9', NULL),
('savoir', '3', 'avoir', '9', NULL),
('devoir', '3', 'avoir', '9', NULL),
('partir', '3', 'être', '9', NULL),
('sortir', '3', 'être', '9', NULL),
('mettre', '3', 'avoir', '9', NULL),
('lire', '3', 'avoir', '9', NULL),
('écrire', '3', 'avoir', '9', NULL),
('croire', '3', 'avoir', '9', NULL),
('boire', '3', 'avoir', '9', NULL),
('dormir', '3', 'avoir', '9', NULL),
('courir', '3', 'avoir', '9', NULL),
('tenir', '3', 'avoir', '9', NULL),
('mourir', '3', 'être', '9', NULL),

-- Pronominaux essentiels
('se lever', '1', 'être', '9', 'pronominal'),
('se coucher', '1', 'être', '9', 'pronominal'),
('se laver', '1', 'être', '9', 'pronominal'),
('se promener', '1', 'être', '9', 'pronominal'),
('se réveiller', '1', 'être', '9', 'pronominal'),
('s''appeler', '1', 'être', '9', 'pronominal'),

-- ============================================
-- VERBES 10e ANNÉE (approfondissement)
-- ============================================

-- 1er groupe - verbes plus complexes
('créer', '1', 'avoir', '10', NULL),
('avouer', '1', 'avoir', '10', NULL),
('continuer', '1', 'avoir', '10', NULL),
('distribuer', '1', 'avoir', '10', NULL),
('habituer', '1', 'avoir', '10', NULL),
('tuer', '1', 'avoir', '10', NULL),
('remuer', '1', 'avoir', '10', NULL),
('saluer', '1', 'avoir', '10', NULL),
('employer', '1', 'avoir', '10', 'y devient i devant e muet'),
('ennuyer', '1', 'avoir', '10', 'y devient i devant e muet'),
('noyer', '1', 'avoir', '10', 'y devient i devant e muet'),
('tutoyer', '1', 'avoir', '10', 'y devient i devant e muet'),
('vouvoyer', '1', 'avoir', '10', 'y devient i devant e muet'),
('côtoyer', '1', 'avoir', '10', 'y devient i devant e muet'),

-- 1er groupe - verbes en é_er
('céder', '1', 'avoir', '10', 'é devient è devant e muet'),
('espérer', '1', 'avoir', '10', 'é devient è devant e muet'),
('préférer', '1', 'avoir', '10', 'é devient è devant e muet'),
('répéter', '1', 'avoir', '10', 'é devient è devant e muet'),
('posséder', '1', 'avoir', '10', 'é devient è devant e muet'),
('exagérer', '1', 'avoir', '10', 'é devient è devant e muet'),

-- 1er groupe - verbes en -eler, -eter (modèles alternatifs)
('modeler', '1', 'avoir', '10', 'accent grave devant e muet'),
('peler', '1', 'avoir', '10', 'accent grave devant e muet'),
('geler', '1', 'avoir', '10', 'accent grave devant e muet'),
('haleter', '1', 'avoir', '10', 'accent grave devant e muet'),

-- 2e groupe - approfondissement
('accomplir', '2', 'avoir', '10', NULL),
('applaudir', '2', 'avoir', '10', NULL),
('approfondir', '2', 'avoir', '10', NULL),
('avertir', '2', 'avoir', '10', NULL),
('bannir', '2', 'avoir', '10', NULL),
('définir', '2', 'avoir', '10', NULL),
('démolir', '2', 'avoir', '10', NULL),
('éblouir', '2', 'avoir', '10', NULL),
('éclaircir', '2', 'avoir', '10', NULL),
('élargir', '2', 'avoir', '10', NULL),
('embellir', '2', 'avoir', '10', NULL),
('enrichir', '2', 'avoir', '10', NULL),
('envahir', '2', 'avoir', '10', NULL),
('établir', '2', 'avoir', '10', NULL),
('garantir', '2', 'avoir', '10', NULL),
('guérir', '2', 'avoir', '10', NULL),
('investir', '2', 'avoir', '10', NULL),
('nourrir', '2', 'avoir', '10', NULL),
('punir', '2', 'avoir', '10', NULL),
('rafraîchir', '2', 'avoir', '10', NULL),
('réagir', '2', 'avoir', '10', NULL),
('réunir', '2', 'avoir', '10', NULL),
('saisir', '2', 'avoir', '10', NULL),
('subir', '2', 'avoir', '10', NULL),
('trahir', '2', 'avoir', '10', NULL),
('unir', '2', 'avoir', '10', NULL),
('vieillir', '2', 'avoir', '10', NULL),

-- 3e groupe - verbes importants
('apercevoir', '3', 'avoir', '10', NULL),
('recevoir', '3', 'avoir', '10', NULL),
('concevoir', '3', 'avoir', '10', NULL),
('décevoir', '3', 'avoir', '10', NULL),
('percevoir', '3', 'avoir', '10', NULL),
('atteindre', '3', 'avoir', '10', NULL),
('craindre', '3', 'avoir', '10', NULL),
('éteindre', '3', 'avoir', '10', NULL),
('peindre', '3', 'avoir', '10', NULL),
('plaindre', '3', 'avoir', '10', NULL),
('joindre', '3', 'avoir', '10', NULL),
('battre', '3', 'avoir', '10', NULL),
('combattre', '3', 'avoir', '10', NULL),
('connaître', '3', 'avoir', '10', NULL),
('paraître', '3', 'avoir', '10', NULL),
('apparaître', '3', 'avoir', '10', NULL),
('disparaître', '3', 'avoir', '10', NULL),
('naître', '3', 'être', '10', NULL),
('conduire', '3', 'avoir', '10', NULL),
('construire', '3', 'avoir', '10', NULL),
('détruire', '3', 'avoir', '10', NULL),
('produire', '3', 'avoir', '10', NULL),
('traduire', '3', 'avoir', '10', NULL),
('introduire', '3', 'avoir', '10', NULL),
('réduire', '3', 'avoir', '10', NULL),
('cuire', '3', 'avoir', '10', NULL),
('nuire', '3', 'avoir', '10', NULL),
('luire', '3', 'avoir', '10', NULL),
('coudre', '3', 'avoir', '10', NULL),
('moudre', '3', 'avoir', '10', NULL),
('résoudre', '3', 'avoir', '10', NULL),
('suivre', '3', 'avoir', '10', NULL),
('poursuivre', '3', 'avoir', '10', NULL),
('vivre', '3', 'avoir', '10', NULL),
('survivre', '3', 'avoir', '10', NULL),
('convaincre', '3', 'avoir', '10', NULL),
('vaincre', '3', 'avoir', '10', NULL),
('plaire', '3', 'avoir', '10', NULL),
('se taire', '3', 'être', '10', 'pronominal'),
('rire', '3', 'avoir', '10', NULL),
('sourire', '3', 'avoir', '10', NULL),
('suffire', '3', 'avoir', '10', NULL),
('conclure', '3', 'avoir', '10', NULL),
('exclure', '3', 'avoir', '10', NULL),
('inclure', '3', 'avoir', '10', NULL),
('interrompre', '3', 'avoir', '10', NULL),
('rompre', '3', 'avoir', '10', NULL),
('corrompre', '3', 'avoir', '10', NULL),

-- Composés de verbes 9e
('revenir', '3', 'être', '10', NULL),
('devenir', '3', 'être', '10', NULL),
('parvenir', '3', 'être', '10', NULL),
('intervenir', '3', 'être', '10', NULL),
('retenir', '3', 'avoir', '10', NULL),
('maintenir', '3', 'avoir', '10', NULL),
('obtenir', '3', 'avoir', '10', NULL),
('soutenir', '3', 'avoir', '10', NULL),
('appartenir', '3', 'avoir', '10', NULL),
('contenir', '3', 'avoir', '10', NULL),
('reprendre', '3', 'avoir', '10', NULL),
('comprendre', '3', 'avoir', '10', NULL),
('apprendre', '3', 'avoir', '10', NULL),
('entreprendre', '3', 'avoir', '10', NULL),
('surprendre', '3', 'avoir', '10', NULL),
('permettre', '3', 'avoir', '10', NULL),
('promettre', '3', 'avoir', '10', NULL),
('admettre', '3', 'avoir', '10', NULL),
('transmettre', '3', 'avoir', '10', NULL),
('soumettre', '3', 'avoir', '10', NULL),
('remettre', '3', 'avoir', '10', NULL),
('commettre', '3', 'avoir', '10', NULL),
('émettre', '3', 'avoir', '10', NULL),
('omettre', '3', 'avoir', '10', NULL),
('revoir', '3', 'avoir', '10', NULL),
('prévoir', '3', 'avoir', '10', NULL),
('pourvoir', '3', 'avoir', '10', NULL),
('entrevoir', '3', 'avoir', '10', NULL),

-- Pronominaux
('se souvenir', '3', 'être', '10', 'pronominal'),
('s''enfuir', '3', 'être', '10', 'pronominal'),
('s''apercevoir', '3', 'être', '10', 'pronominal'),
('se plaindre', '3', 'être', '10', 'pronominal'),
('se méfier', '1', 'être', '10', 'pronominal'),
('se servir', '3', 'être', '10', 'pronominal'),

-- ============================================
-- VERBES 11e ANNÉE (maîtrise avancée)
-- ============================================

-- 1er groupe - verbes littéraires/soutenus
('octroyer', '1', 'avoir', '11', 'y devient i devant e muet'),
('foudroyer', '1', 'avoir', '11', 'y devient i devant e muet'),
('louvoyer', '1', 'avoir', '11', 'y devient i devant e muet'),
('festoyer', '1', 'avoir', '11', 'y devient i devant e muet'),
('guerroyer', '1', 'avoir', '11', 'y devient i devant e muet'),
('chatoyer', '1', 'avoir', '11', 'y devient i devant e muet'),
('flamboyer', '1', 'avoir', '11', 'y devient i devant e muet'),
('côtoyer', '1', 'avoir', '11', 'y devient i devant e muet'),
('apitoyer', '1', 'avoir', '11', 'y devient i devant e muet'),
('convoyer', '1', 'avoir', '11', 'y devient i devant e muet'),

-- 2e groupe - verbes moins courants
('accomplir', '2', 'avoir', '11', NULL),
('affranchir', '2', 'avoir', '11', NULL),
('anéantir', '2', 'avoir', '11', NULL),
('asservir', '2', 'avoir', '11', NULL),
('assombrir', '2', 'avoir', '11', NULL),
('assortir', '2', 'avoir', '11', NULL),
('assoupir', '2', 'avoir', '11', NULL),
('assouplir', '2', 'avoir', '11', NULL),
('assourdir', '2', 'avoir', '11', NULL),
('assouvir', '2', 'avoir', '11', NULL),
('attendrir', '2', 'avoir', '11', NULL),
('atterrir', '2', 'avoir', '11', NULL),
('blanchir', '2', 'avoir', '11', NULL),
('blêmir', '2', 'avoir', '11', NULL),
('brunir', '2', 'avoir', '11', NULL),
('durcir', '2', 'avoir', '11', NULL),
('épaissir', '2', 'avoir', '11', NULL),
('faiblir', '2', 'avoir', '11', NULL),
('fleurir', '2', 'avoir', '11', NULL),
('fléchir', '2', 'avoir', '11', NULL),
('franchir', '2', 'avoir', '11', NULL),
('frémir', '2', 'avoir', '11', NULL),
('gémir', '2', 'avoir', '11', NULL),
('gravir', '2', 'avoir', '11', NULL),
('jaillir', '2', 'avoir', '11', NULL),
('jaunir', '2', 'avoir', '11', NULL),
('languir', '2', 'avoir', '11', NULL),
('mûrir', '2', 'avoir', '11', NULL),
('noircir', '2', 'avoir', '11', NULL),
('obéir', '2', 'avoir', '11', NULL),
('pâlir', '2', 'avoir', '11', NULL),
('périr', '2', 'avoir', '11', NULL),
('polir', '2', 'avoir', '11', NULL),
('pourrir', '2', 'avoir', '11', NULL),
('raccourcir', '2', 'avoir', '11', NULL),
('raidir', '2', 'avoir', '11', NULL),
('rajeunir', '2', 'avoir', '11', NULL),
('ralentir', '2', 'avoir', '11', NULL),
('ramollir', '2', 'avoir', '11', NULL),
('ravir', '2', 'avoir', '11', NULL),
('rebondir', '2', 'avoir', '11', NULL),
('refroidir', '2', 'avoir', '11', NULL),
('rejaillir', '2', 'avoir', '11', NULL),
('renchérir', '2', 'avoir', '11', NULL),
('resplendir', '2', 'avoir', '11', NULL),
('ressortir', '2', 'être', '11', '3e groupe sens "sortir à nouveau"'),
('retentir', '2', 'avoir', '11', NULL),
('rétrécir', '2', 'avoir', '11', NULL),
('rougir', '2', 'avoir', '11', NULL),
('rugir', '2', 'avoir', '11', NULL),
('sévir', '2', 'avoir', '11', NULL),
('surgir', '2', 'avoir', '11', NULL),
('ternir', '2', 'avoir', '11', NULL),
('tiédir', '2', 'avoir', '11', NULL),
('verdir', '2', 'avoir', '11', NULL),
('vernir', '2', 'avoir', '11', NULL),

-- 3e groupe - verbes rares/littéraires
('absoudre', '3', 'avoir', '11', 'pas de passé simple'),
('acquérir', '3', 'avoir', '11', NULL),
('conquérir', '3', 'avoir', '11', NULL),
('requérir', '3', 'avoir', '11', NULL),
('s''enquérir', '3', 'être', '11', 'pronominal'),
('asseoir', '3', 'avoir', '11', 'deux conjugaisons'),
('choir', '3', 'être', '11', 'défectif'),
('déchoir', '3', 'être', '11', 'défectif'),
('échoir', '3', 'être', '11', 'défectif'),
('clore', '3', 'avoir', '11', 'défectif'),
('enclore', '3', 'avoir', '11', 'défectif'),
('éclore', '3', 'être', '11', 'défectif'),
('circonscrire', '3', 'avoir', '11', NULL),
('prescrire', '3', 'avoir', '11', NULL),
('proscrire', '3', 'avoir', '11', NULL),
('inscrire', '3', 'avoir', '11', NULL),
('transcrire', '3', 'avoir', '11', NULL),
('souscrire', '3', 'avoir', '11', NULL),
('décrire', '3', 'avoir', '11', NULL),
('croître', '3', 'avoir', '11', NULL),
('accroître', '3', 'avoir', '11', NULL),
('décroître', '3', 'avoir', '11', NULL),
('émouvoir', '3', 'avoir', '11', NULL),
('promouvoir', '3', 'avoir', '11', NULL),
('mouvoir', '3', 'avoir', '11', NULL),
('gésir', '3', 'avoir', '11', 'défectif'),
('haïr', '3', 'avoir', '11', 'tréma'),
('oindre', '3', 'avoir', '11', 'rare'),
('poindre', '3', 'avoir', '11', 'défectif'),
('paître', '3', 'avoir', '11', 'défectif'),
('repaître', '3', 'avoir', '11', NULL),
('quérir', '3', 'avoir', '11', 'défectif, infinitif seulement'),
('seoir', '3', 'avoir', '11', 'défectif'),
('surseoir', '3', 'avoir', '11', NULL),
('traire', '3', 'avoir', '11', 'pas de passé simple'),
('extraire', '3', 'avoir', '11', 'pas de passé simple'),
('soustraire', '3', 'avoir', '11', 'pas de passé simple'),
('distraire', '3', 'avoir', '11', 'pas de passé simple'),
('abstraire', '3', 'avoir', '11', 'pas de passé simple'),

-- Verbes en -oudre (compléments)
('dissoudre', '3', 'avoir', '11', NULL),

-- Pronominaux littéraires
('se repentir', '3', 'être', '11', 'pronominal'),
('s''abstenir', '3', 'être', '11', 'pronominal'),
('se départir', '3', 'être', '11', 'pronominal'),
('se prévaloir', '3', 'être', '11', 'pronominal');
